/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.node;

import compiladores2.analysis.*;

@SuppressWarnings("nls")
public final class AAfectacaoInst extends PInst
{
    private PAfect _afect_;

    public AAfectacaoInst()
    {
        // Constructor
    }

    public AAfectacaoInst(
        @SuppressWarnings("hiding") PAfect _afect_)
    {
        // Constructor
        setAfect(_afect_);

    }

    @Override
    public Object clone()
    {
        return new AAfectacaoInst(
            cloneNode(this._afect_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAfectacaoInst(this);
    }

    public PAfect getAfect()
    {
        return this._afect_;
    }

    public void setAfect(PAfect node)
    {
        if(this._afect_ != null)
        {
            this._afect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._afect_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._afect_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._afect_ == child)
        {
            this._afect_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._afect_ == oldChild)
        {
            setAfect((PAfect) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
