/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.node;

import compiladores2.analysis.*;

@SuppressWarnings("nls")
public final class ACicloInst extends PInst
{
    private PCiclo _ciclo_;

    public ACicloInst()
    {
        // Constructor
    }

    public ACicloInst(
        @SuppressWarnings("hiding") PCiclo _ciclo_)
    {
        // Constructor
        setCiclo(_ciclo_);

    }

    @Override
    public Object clone()
    {
        return new ACicloInst(
            cloneNode(this._ciclo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACicloInst(this);
    }

    public PCiclo getCiclo()
    {
        return this._ciclo_;
    }

    public void setCiclo(PCiclo node)
    {
        if(this._ciclo_ != null)
        {
            this._ciclo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ciclo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ciclo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ciclo_ == child)
        {
            this._ciclo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ciclo_ == oldChild)
        {
            setCiclo((PCiclo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
