/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.node;

import compiladores2.analysis.*;

@SuppressWarnings("nls")
public final class AFloatExp extends PExp
{
    private TFloatProd _floatProd_;

    public AFloatExp()
    {
        // Constructor
    }

    public AFloatExp(
        @SuppressWarnings("hiding") TFloatProd _floatProd_)
    {
        // Constructor
        setFloatProd(_floatProd_);

    }

    @Override
    public Object clone()
    {
        return new AFloatExp(
            cloneNode(this._floatProd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatExp(this);
    }

    public TFloatProd getFloatProd()
    {
        return this._floatProd_;
    }

    public void setFloatProd(TFloatProd node)
    {
        if(this._floatProd_ != null)
        {
            this._floatProd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatProd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatProd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatProd_ == child)
        {
            this._floatProd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatProd_ == oldChild)
        {
            setFloatProd((TFloatProd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
