/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.node;

import compiladores2.analysis.*;

@SuppressWarnings("nls")
public final class ANextInst extends PInst
{
    private TNext _next_;

    public ANextInst()
    {
        // Constructor
    }

    public ANextInst(
        @SuppressWarnings("hiding") TNext _next_)
    {
        // Constructor
        setNext(_next_);

    }

    @Override
    public Object clone()
    {
        return new ANextInst(
            cloneNode(this._next_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextInst(this);
    }

    public TNext getNext()
    {
        return this._next_;
    }

    public void setNext(TNext node)
    {
        if(this._next_ != null)
        {
            this._next_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._next_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._next_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._next_ == child)
        {
            this._next_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._next_ == oldChild)
        {
            setNext((TNext) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
