/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.node;

import java.util.*;
import compiladores2.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private final LinkedList<PInst> _inst_ = new LinkedList<PInst>();

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") List<?> _inst_)
    {
        // Constructor
        setInst(_inst_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneList(this._inst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public LinkedList<PInst> getInst()
    {
        return this._inst_;
    }

    public void setInst(List<?> list)
    {
        for(PInst e : this._inst_)
        {
            e.parent(null);
        }
        this._inst_.clear();

        for(Object obj_e : list)
        {
            PInst e = (PInst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._inst_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inst_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PInst> i = this._inst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
