/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores2.parser;

import compiladores2.node.*;
import compiladores2.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLBrac(@SuppressWarnings("unused") TLBrac node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRBrac(@SuppressWarnings("unused") TRBrac node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLSbrac(@SuppressWarnings("unused") TLSbrac node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRSbrac(@SuppressWarnings("unused") TRSbrac node)
    {
        this.index = 5;
    }

    @Override
    public void caseTComa(@SuppressWarnings("unused") TComa node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 8;
    }

    @Override
    public void caseTIgu(@SuppressWarnings("unused") TIgu node)
    {
        this.index = 9;
    }

    @Override
    public void caseTCol(@SuppressWarnings("unused") TCol node)
    {
        this.index = 10;
    }

    @Override
    public void caseTDdot(@SuppressWarnings("unused") TDdot node)
    {
        this.index = 11;
    }

    @Override
    public void caseTExcl(@SuppressWarnings("unused") TExcl node)
    {
        this.index = 12;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 13;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 14;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 15;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 16;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 17;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 18;
    }

    @Override
    public void caseTPot(@SuppressWarnings("unused") TPot node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 21;
    }

    @Override
    public void caseTEqu(@SuppressWarnings("unused") TEqu node)
    {
        this.index = 22;
    }

    @Override
    public void caseTMenequ(@SuppressWarnings("unused") TMenequ node)
    {
        this.index = 23;
    }

    @Override
    public void caseTMaiequ(@SuppressWarnings("unused") TMaiequ node)
    {
        this.index = 24;
    }

    @Override
    public void caseTDif(@SuppressWarnings("unused") TDif node)
    {
        this.index = 25;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 26;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 27;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 28;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 29;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 30;
    }

    @Override
    public void caseTFloat(@SuppressWarnings("unused") TFloat node)
    {
        this.index = 31;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 32;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 33;
    }

    @Override
    public void caseTVoid(@SuppressWarnings("unused") TVoid node)
    {
        this.index = 34;
    }

    @Override
    public void caseTDefine(@SuppressWarnings("unused") TDefine node)
    {
        this.index = 35;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 36;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 37;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 38;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 39;
    }

    @Override
    public void caseTDo(@SuppressWarnings("unused") TDo node)
    {
        this.index = 40;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 41;
    }

    @Override
    public void caseTBreak(@SuppressWarnings("unused") TBreak node)
    {
        this.index = 42;
    }

    @Override
    public void caseTNext(@SuppressWarnings("unused") TNext node)
    {
        this.index = 43;
    }

    @Override
    public void caseTVariavel(@SuppressWarnings("unused") TVariavel node)
    {
        this.index = 44;
    }

    @Override
    public void caseTInteger(@SuppressWarnings("unused") TInteger node)
    {
        this.index = 45;
    }

    @Override
    public void caseTFloatProd(@SuppressWarnings("unused") TFloatProd node)
    {
        this.index = 46;
    }

    @Override
    public void caseTStringProd(@SuppressWarnings("unused") TStringProd node)
    {
        this.index = 47;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 48;
    }
}
